<template>
  <AlertBox />
  <table class="table-borderless text-left">
    <tr>
      <th>Question Number:</th>
      <td>
        <input id="questionNumber" v-model="questionNumber" class="form-control" placeholder="Question Number"
               type="number" required/>
      </td>
    </tr>
    <tr>
      <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
      <th>Question Type:</th>
      <td>
        <select id="questionType" v-model="questionType" class="form-select form-select" required>
          <option v-for="qType in questionTypes" v-bind:key="qType.text" :value="qType.value">
            {{ qType.text }}
          </option>
        </select>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>Slug (Autogenerated):</th>
      <td>
        <p class="alert-secondary alert text-success">{{ getQuestionSlug }}</p>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>Question Title (English):</th>
      <td>
        <textarea id="questionTitleEnglish" v-model="questionTitleEnglish" class="form-control"
                  name="questionTitleEnglish"
                  rows="3" @keyup="createSlug"></textarea>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>Question Title (Vietnamese):</th>
      <td>
        <textarea id="questionTitleVietnamese" v-model="questionTitleVietnamese" class="form-control"
                  name="questionTitleVietnamese"
                  rows="3"></textarea>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>Answers:</th>
      <td>
        <div class="card card-body bg-info">
          <div class="row">
            <div class="col-auto">
              <div v-for="(answer, index) in getAnswers" v-bind:key="index" class="row border-bottom border-1">
                <div class="col">
                  <input :value="answer.answerValue"
                         class="form-control mt-1"
                         placeholder="Value (in English)" type="text"/>

                </div>

                <div class="col mt-2">
                  <input :value="answer.answerTitleEnglish"
                         class="form-control"
                         placeholder="Text (English)" type="text"/>
                  <input :value="answer.answerTitleVietnamese"
                         class="form-control mb-2" placeholder="Text (Vietnamese)" type="text"/>
                </div>

                <div v-if="index !== 0" class="col mt-2">
                  <button class="btn btn-danger material-icons text-white text-decoration-none"
                          @click="removeAnswer(index)">
                    remove
                  </button>
                </div>

              </div>
            </div>

            <div class="col-auto">
              <button class="btn btn-success material-icons text-white text-decoration-none" @click="addAnswer">
                add
              </button> &nbsp;

            </div>

          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>Additional Information (English):</th>
      <td>
        <textarea id="additionalInformationEnglish" v-model="additionalInformationEnglish" class="form-control"
                  name="additionalInformationEnglish"
                  rows="3"></textarea>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>Additional Information (Vietnamese):</th>
      <td>
        <textarea id="additionalInformationVietnamese" v-model="additionalInformationVietnamese" class="form-control"
                  name="additionalInformationVietnamese"
                  rows="3"></textarea>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>
        <button class="btn btn-success" @click="saveQuestion">Save</button>&nbsp;&nbsp;
        <button class="btn btn-danger" @click="$router.push('/question')">Cancel</button>
      </td>
    </tr>
  </table>

</template>

<script>
import {mapActions, mapGetters} from "vuex";
import {mapFields} from 'vuex-map-fields';
import AlertBox from "@/components/util/AlertBox";

export default {
  name: "QuestionForm",
  components: {
    AlertBox
  },
  methods: {
    ...mapActions(['fetchQuestionById', 'createSlug', 'addNewAnswer', 'removeExistingAnswer', 'saveQuestion']),
    addAnswer() {
      this.addNewAnswer(
          {
            answerValueEnglish: '',
            answerValueVietnamese: ''
          }
      );
    },
    removeAnswer(index) {
      this.removeExistingAnswer(index)
    }
  },
  data() {
    return {
      questionTypes: [
        {
          text: "Select question type",
          value: "",
        },
        {
          text: "Scale",
          value: "scale",
        },
        {
          text: "Select",
          value: "select",
        },
      ]
    };
  },
  mounted() {
    if (this.$route.params.id) {
      console.log("edit");
      this.fetchQuestionById(this.$route.params.id);
    }
  },
  computed: {
    ...mapFields(
        [
          'questionType',
          'questionNumber',
          'questionTitleEnglish',
          'questionTitleVietnamese',
          'additionalInformationEnglish',
          'additionalInformationVietnamese'
        ]
    ),
    ...mapGetters(['getQuestionSlug', 'getAnswers'])
  }
}
</script>

<style scoped>
table td, table th {
  text-align: left;
  min-width: 50px !important;
}
</style>