<template>
  <AlertBox/>
  <form @submit="submitForm">

    <div class="row g3">
      <div class="col-md-6">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label"
                 for="questionNumber">Question
            Number:</label>
          <div class="col-sm-9">
            <input id="questionNumber" v-model="questionNumber" class="form-control form-control-sm"
                   placeholder="Question Number"
                   required type="number"/>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label" for="questionSlug">Slug
            (Autogenerated):</label>
          <p id="questionSlug" class="alert-secondary alert text-success col-sm-9">{{ getQuestionSlug }}</p>
        </div>
      </div>

      <div class="col-md-6 form-group required">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">Question
            Title</label>
          <div class="col-sm-4">
             <textarea id="questionTitleEnglish" v-model="questionTitleEnglish" class="form-control"
                       name="questionTitleEnglish" placeholder="English"
                       required rows="3" @keyup="createSlug"></textarea>
          </div>
          <div class="col-sm-4">
            <textarea id="questionTitleVietnamese" v-model="questionTitleVietnamese" class="form-control"
                      name="questionTitleVietnamese" placeholder="Vietnamese"
                      rows="3"></textarea>
          </div>
        </div>

      </div>

      <div class="col-md-6 form-group required">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">Additional
            Information: </label>
          <div class="col-sm-4">
            <textarea id="additionalInformationEnglish" v-model="additionalInformationEnglish" class="form-control"
                      name="additionalInformationEnglish" placeholder="English"
                      rows="3"></textarea>
          </div>
          <div class="col-sm-4">
             <textarea id="additionalInformationVietnamese" v-model="additionalInformationVietnamese"
                       class="form-control"
                       name="additionalInformationVietnamese"
                       placeholder="Vietnamese"
                       rows="3"></textarea>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="row mt-4">
          <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">
            Question Type:
          </label>
          <div class="col-sm-9">
            <select id="questionType" v-model="questionType" class="form-select form-select-sm" required @change="reloadAnswerList">
              <option v-for="qType in questionTypes" v-bind:key="qType._id" :value="qType.questionType">
                {{ qType.questionType }}
              </option>
            </select>
          </div>
        </div>
      </div>
      <div class="col-md-6">&nbsp;</div>
      <div class="col-md-6 mt-4">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">
            Answers Text:
          </label>
          <div class="col-sm-9">
            <div class="row card text-dark">
              <div v-for="answerValue in selectedQuestionType.answerValues" :key="answerValue" class="col-sm-auto">
                <label class="form-label control-label fw-bolder">{{ answerValue }}</label>
                <div class="row card-body">
                  <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">
                    English
                  </label>
                  <div class="col-md-9 mb-2">
                    <input class="form-control" required type="text"/>
                  </div>

                  <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">
                    Vietnamese
                  </label>
                  <div class="col-md-9">
                    <input class="form-control" type="text"/></div>
                </div>

              </div>

            </div>
          </div>

        </div>
      </div>
    </div>
    <hr/>
    <div class="mb-5 row">
      <button class="col-auto btn btn-success" type="submit">Save</button>&nbsp;&nbsp;
      <button class="col-auto btn btn-danger" @click="$router.push('/question')">Cancel</button>
    </div>

  </form>

</template>

<script>
import {mapActions, mapGetters} from "vuex";
import AlertBox from "@/components/util/AlertBox";

export default {
  name: "QuestionForm",
  components: {
    AlertBox
  },
  methods: {
    ...mapActions({
      fetchQuestionTypes: 'questionForm/fetchQuestionTypes',
      fetchQuestionById: 'questionForm/fetchQuestionById',
      createSlug: 'questionForm/createSlug',
      addNewAnswer: 'questionForm/addNewAnswer',
      removeExistingAnswer: 'questionForm/removeExistingAnswer',
      saveQuestion: 'questionForm/saveQuestion',
      updateAnswerFieldByInde: 'questionForm/updateAnswerFieldByIndex',
      reloadAnswerList: 'questionForm/reloadAnswerList'
    }),
    submitForm(event) {
      this.saveQuestion();
      event.preventDefault();
    },
    updateAnswer(event, answerIndex, fieldName) {
      this.updateAnswerFieldByIndex(
          {
            index: answerIndex,
            fieldName: fieldName,
            value: event.currentTarget.value
          }
      );
    },
    removeAnswer(index) {
      this.removeExistingAnswer(index)
    }
  },
  mounted() {
    this.$store.dispatch('hideAlert');
    if (this.$route.params.id) {
      this.fetchQuestionById(this.$route.params.id);
    }
    this.fetchQuestionTypes();
  },
  computed: {
    ...mapGetters({
      getQuestionSlug: 'questionForm/getQuestionSlug',
      getAnswers: 'questionForm/getAnswers',
      questionTypes: 'questionForm/questionTypes',
      selectedQuestionType: 'questionForm/selectedQuestionType'
    }),
    questionType: {
      get() {
        return this.$store.state.questionForm.questionType
      },
      set(value) {
        this.$store.commit('questionForm/UPDATE_QUESTION_TYPE', value)
      }
    },
    questionNumber: {
      get() {
        return this.$store.state.questionForm.questionNumber
      },
      set(value) {
        this.$store.commit('UPDATE_QUESTION_NUMBER', value)
      }
    },
    questionTitleEnglish: {
      get() {
        return this.$store.state.questionForm.questionTitleEnglish
      },
      set(value) {
        this.$store.commit('UPDATE_QUESTION_TITLE_ENGLISH', value)
      }
    },
    questionTitleVietnamese: {
      get() {
        return this.$store.state.questionForm.questionTitleVietnamese
      },
      set(value) {
        this.$store.commit('UPDATE_QUESTION_TITLE_VIETNAMESE', value)
      }
    },
    additionalInformationEnglish: {
      get() {
        return this.$store.state.questionForm.additionalInformationEnglish
      },
      set(value) {
        this.$store.commit('questionForm/UPDATE_ADDITIONAL_INFORMATION_ENGLISH', value)
      }
    },
    additionalInformationVietnamese: {
      get() {
        return this.$store.state.questionForm.additionalInformationVietnamese
      },
      set(value) {
        this.$store.commit('questionForm/UPDATE_ADDITIONAL_INFORMATION_VIETNAMESE', value)
      }
    }
  }
}
</script>

<style scoped>
table td, table th {
  text-align: left;
  min-width: 50px !important;
}

.form-group.required .control-label:after {
  content: "*";
  color: #f80202;
  font-size: 20px;
}
</style>