<template>
  <AlertBox/>
  <form @submit="submitForm">

    <div class="row g3">
      <div class="col-md-6">
        <div class="row mb-3">
          <label class="col-sm-3 col-form-label col-form-label-sm text-start" for="questionNumber">
            Languages:
          </label>
          <div class="col-sm-9">
            <div class="card">
              <div class="card-body">
                <div v-for="language in supportedLanguages" :key="language" class="input-group mb-3">
                  <span id="language-english" class="input-group-text">
                    <input v-bind:id="language.value" v-model="language.isSelected" name="language"
                           type="checkbox" v-bind:value="language.value" @change="languagesChanged"/>
                  </span>
                  <label aria-describedby="language-english" aria-label="Language English" class="form-control"
                         type="text">{{ language.text }}</label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6">&nbsp;</div>

      <div class="col-md-6">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm text-start" for="questionNumber">
            Question Number:
          </label>
          <div class="col-sm-9">
            <input id="questionNumber" v-model="questionNumber" class="form-control form-control-sm"
                   placeholder="Question Number"
                   required type="number"/>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm text-start" for="questionSlug">
            Slug (Autogenerated):
          </label>
          <p id="questionSlug" class="alert-secondary alert text-success col-sm-9">{{ getQuestionSlug }}</p>
        </div>
      </div>

      <div class="col-md-6 form-group required">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm text-start">Question Title</label>

          <template v-for="(questionTitle, index) in questionTitles" :key="index">
            <div class="col-sm-9 mb-1">
             <textarea v-model="questionTitle.value" :placeholder="questionTitle.language"
                       class="form-control"
                       rows="3" @keyup="createSlug"></textarea>
            </div>
            <div class="col-sm-3">&nbsp;</div>
          </template>

        </div>
      </div>

      <div class="col-md-6">&nbsp;</div>

      <div class="col-md-6 mt-3">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm text-start">Additional Information:</label>

          <template v-for="(additionalInformation, index) in additionalInformationList" :key="index">
            <div class="col-sm-9 mb-1">
              <textarea v-model="additionalInformation.value" class="form-control" :placeholder="additionalInformation.language"
                        rows="3"></textarea>
            </div>
            <div class="col-sm-3">&nbsp;</div>
          </template>
        </div>
      </div>

      <div class="col-md-6">&nbsp;</div>

      <div class="col-md-6">
        <div class="row mt-4">
          <label class="col-sm-3 col-form-label col-form-label-sm text-start">
            Question Type:
          </label>
          <div class="col-sm-9">
            <select id="questionType" v-model="questionType" class="form-select form-select-sm" required
                    @change="reloadAnswerList">
              <option v-for="answerType in answerTypes" v-bind:key="answerType._id" :value="answerType.answerType">
                {{ answerType.answerType }}
              </option>
            </select>
          </div>
        </div>
      </div>
      <div class="col-md-6"> &nbsp;</div>
      <div class="col-md-6 mt-4">
        <div class="row">
          <label class="col-sm-3 col-form-label col-form-label-sm text-start">
            Answers:
          </label>
          <div class="col-sm-9">
            <div class="row card text-dark">
              <div v-for="answerValue in selectedQuestionType.answerValues" :key="answerValue" class="col-sm-auto">
                <label class="form-label control-label fw-bolder">{{ answerValue }}</label>
                <div class="row card-body">
                  <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">
                    English
                  </label>
                  <div class="col-md-9 mb-2">
                    <input class="form-control" required type="text"/>
                  </div>

                  <label class="col-sm-3 col-form-label col-form-label-sm question-form-label control-label">
                    Vietnamese
                  </label>
                  <div class="col-md-9">
                    <input class="form-control" type="text"/></div>
                </div>

              </div>

            </div>
          </div>

        </div>
      </div>
    </div>
    <hr/>
    <div class="ms-3 mb-5 row">
      <button class="col-auto btn btn-success" type="submit">Save</button>&nbsp;&nbsp;
      <button class="col-auto btn btn-danger" @click="$router.push('/question')">Cancel</button>
    </div>

  </form>

</template>

<script>
import {mapActions, mapGetters} from "vuex";
import AlertBox from "@/components/util/AlertBox";

export default {
  name: "QuestionForm",
  components: {
    AlertBox
  },
  methods: {
    ...mapActions({
      languagesChanged: 'questionForm/languagesChanged',
      fetchAnswerTypes: 'questionForm/fetchAnswerTypes',
      fetchQuestionById: 'questionForm/fetchQuestionById',
      createSlug: 'questionForm/createSlug',
      addNewAnswer: 'questionForm/addNewAnswer',
      removeExistingAnswer: 'questionForm/removeExistingAnswer',
      saveQuestion: 'questionForm/saveQuestion',
      reloadAnswerList: 'questionForm/reloadAnswerList'
    }),

    generateTitles() {
      const supportedLanguages = this.supportedLanguages.filter(language => language.isSelected);
      console.log(supportedLanguages);

      return 'test';
    },


    submitForm(event) {
      this.saveQuestion();
      event.preventDefault();
    },
  },
  mounted() {
    this.$store.dispatch('hideAlert');
    if (this.$route.params.id) {
      this.fetchQuestionById(this.$route.params.id);
    }
    this.fetchAnswerTypes();
  },
  computed: {
    ...mapGetters({
      getQuestionSlug: 'questionForm/getQuestionSlug',
      getAnswers: 'questionForm/getAnswers',
      answerTypes: 'questionForm/answerTypes',
      selectedQuestionType: 'questionForm/selectedQuestionType',
      supportedLanguages: 'questionForm/supportedLanguages',
      questionTitles: 'questionForm/questionTitles',
      additionalInformationList: 'questionForm/additionalInformationList'
    }),
    questionType: {
      get() {
        return this.$store.state.questionForm.questionType
      },
      set(value) {
        this.$store.commit('questionForm/UPDATE_QUESTION_TYPE', value)
      }
    },
    questionNumber: {
      get() {
        return this.$store.state.questionForm.questionNumber
      },
      set(value) {
        this.$store.commit('UPDATE_QUESTION_NUMBER', value)
      }
    },
    questionTitleEnglish: {
      get() {
        return this.$store.state.questionForm.questionTitleEnglish
      },
      set(value) {
        this.$store.commit('UPDATE_QUESTION_TITLE_ENGLISH', value)
      }
    },
    questionTitleVietnamese: {
      get() {
        return this.$store.state.questionForm.questionTitleVietnamese
      },
      set(value) {
        this.$store.commit('UPDATE_QUESTION_TITLE_VIETNAMESE', value)
      }
    },
    additionalInformationEnglish: {
      get() {
        return this.$store.state.questionForm.additionalInformationEnglish
      },
      set(value) {
        this.$store.commit('questionForm/UPDATE_ADDITIONAL_INFORMATION_ENGLISH', value)
      }
    },
    additionalInformationVietnamese: {
      get() {
        return this.$store.state.questionForm.additionalInformationVietnamese
      },
      set(value) {
        this.$store.commit('questionForm/UPDATE_ADDITIONAL_INFORMATION_VIETNAMESE', value)
      }
    }
  }
}
</script>

<style scoped>
table td, table th {
  text-align: left;
  min-width: 50px !important;
}

.question-number-label {
}

.form-group.required .control-label:after {
  content: "*";
  color: #f80202;
  font-size: 20px;
}
</style>